
spring:
  application:
    name: cloud-zuul
server:
  port: 9091

# Tips:
# 1.注册进 eureka 后，通过服务名调用，不需要手动配置路由
# 2.如果想把 zuul 单独拿来用，需要手动配置路由规则
#zuul:
#  routes:
#    member_api:
#      path: /member/**
#      url: http://localhost:8089/member
#    verify_api:
#      path: /verify/**
#      url: http://localhost:8086/verify

eureka:
  client:
    service-url:
          defaultZone: http://hero:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        # 默认 90 秒
        lease-expiration-duration-in-seconds: 5
        # 默认 30 秒
        lease-renewal-interval-in-seconds: 5

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh,health,info
